name: CI/CD to Yandex Cloud
on:
  push:
    branches: [ main ]
    paths:
      - 'bonus-service/**'
      - '.github/workflows/ci-cd-yandex_cloud.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'bonus-service/**'
      - '.github/workflows/ci-cd-yandex_cloud.yml'

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r bonus-service/requirements-test.txt

      - name: Run unit tests
        working-directory: bonus-service
        run: pytest -m unit

  build:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        working-directory: bonus-service
        run: |
          docker build . --tag bonus-service:latest
          docker save bonus-service:latest -o bonus-service.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bonus-service-image
          path: bonus-service/bonus-service.tar
          retention-days: 1

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: bonus-service-image
          path: bonus-service

      - name: Login to YC Registry
        uses: docker/login-action@v3
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.YC_KEYS }}

      - name: Push to YC Registry
        working-directory: bonus-service
        run: |
          docker load --input bonus-service.tar
          docker tag bonus-service:latest cr.yandex/${{ secrets.YC_REGISTRY_ID }}/bonus-service:latest
          docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/bonus-service:latest

  deploy:
    needs: push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy serverless container
        uses: yc-actions/yc-sls-container-deploy@v4
        with:
          yc-sa-json-credentials: ${{ secrets.YC_KEYS }}
          container-name: ${{ secrets.YC_CONTAINER_NAME }}
          folder-id: ${{ secrets.YC_FOLDER_ID }}
          revision-image-url: cr.yandex/${{ secrets.YC_REGISTRY_ID }}/bonus-service:latest
          revision-service-account-id: ${{ secrets.YC_SA_ID }}
          revision-memory: 256Mb
          revision-env: |
            AMQP_URL=${{ secrets.ENV_AMQP_URL }}
